### ISSUE TITLE
Inquiry Regarding Intel M.2 Modem Side Code for IOSM Driver Adaptation

### ISSUE THREAD

**Issue by Roger-Hoo3** [x42/net-wwan-iosm#1]
I am currently adapting the IOSM Driver to a new chip platform,and as the driver functions on the host side, I was wondering if there is any available reference code for the Intel M.2 Modem side that could assist in this adaptation process.
Your guidance or references to any relevant material would be greatly appreciated.

**Comment by x42** [comment]
This repo is was just a collecting patches done by others. Please see
https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/issues/258#note_827077

**Comment by Roger-Hoo3** [comment]
Thank you for your reply! I will check the link you provided for more details.
